/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panels;

import com.mycompany.pr_dam_p5_gabriel_david.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 * Clase que representa el menú de Alta de animales del centro de recuperación de fauna.
 * En el Se puede dar de Alta un animal introduciendo su nombre, su peso(Kg), la fecha de entrada al refugio (dd/mm/yyyy), su raza, el tipo de lesión,
 * la especie a la que pertenece, la gravedad de la lesión y si es causada o no por el motivo característico de la especie.
 * 
 * @author David López Corella
 * @author Jesús Gabriel Pollos Villazón
 */
public class altaPanel extends javax.swing.JPanel {

    /**
     * Creates new form altaPanel
     */
    public altaPanel() {
        initComponents();

        gravedadComboBox.setSelectedIndex(-1);
        motivoEspecialCheckBox.setText("Elige una especie");
        motivoEspecialCheckBox.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        altaTitle = new javax.swing.JLabel();
        crearAltaBtn = new javax.swing.JButton();
        nameTxt = new javax.swing.JLabel();
        nameTxtField = new javax.swing.JTextField();
        razaTxt = new javax.swing.JLabel();
        lesionTxt = new javax.swing.JLabel();
        lesionTxtField = new javax.swing.JTextField();
        fechaEntradaTxt = new javax.swing.JLabel();
        fechaEntradaTxtField = new javax.swing.JTextField();
        pesoTxt = new javax.swing.JLabel();
        pesoTxtField = new javax.swing.JTextField();
        especieTxt = new javax.swing.JLabel();
        especieComboBox = new javax.swing.JComboBox<>();
        motivoEspecialTxt = new javax.swing.JLabel();
        gravedadTxt = new javax.swing.JLabel();
        gravedadComboBox = new javax.swing.JComboBox<>();
        razaTxtField1 = new javax.swing.JTextField();
        motivoEspecialCheckBox = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(550, 500));

        altaTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        altaTitle.setForeground(new java.awt.Color(51, 153, 255));
        altaTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        altaTitle.setText("Alta de un animal");

        crearAltaBtn.setBackground(new java.awt.Color(0, 102, 255));
        crearAltaBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        crearAltaBtn.setForeground(new java.awt.Color(255, 255, 255));
        crearAltaBtn.setText("CREAR ALTA");
        crearAltaBtn.setBorder(null);
        crearAltaBtn.setPreferredSize(new java.awt.Dimension(150, 40));
        crearAltaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearAltaBtnActionPerformed(evt);
            }
        });

        nameTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nameTxt.setText("Nombre");
        nameTxt.setPreferredSize(new java.awt.Dimension(90, 30));

        nameTxtField.setBackground(new java.awt.Color(232, 232, 232));
        nameTxtField.setForeground(new java.awt.Color(153, 153, 153));
        nameTxtField.setBorder(null);

        razaTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        razaTxt.setText("Raza");
        razaTxt.setPreferredSize(new java.awt.Dimension(90, 30));

        lesionTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lesionTxt.setText("Tipo de lesión");
        lesionTxt.setPreferredSize(new java.awt.Dimension(90, 30));

        lesionTxtField.setBackground(new java.awt.Color(232, 232, 232));
        lesionTxtField.setForeground(new java.awt.Color(153, 153, 153));
        lesionTxtField.setBorder(null);
        lesionTxtField.setMinimumSize(new java.awt.Dimension(240, 29));
        lesionTxtField.setPreferredSize(new java.awt.Dimension(240, 29));

        fechaEntradaTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fechaEntradaTxt.setText("Fecha de entrada");
        fechaEntradaTxt.setPreferredSize(new java.awt.Dimension(90, 30));

        fechaEntradaTxtField.setBackground(new java.awt.Color(232, 232, 232));
        fechaEntradaTxtField.setForeground(new java.awt.Color(153, 153, 153));
        fechaEntradaTxtField.setText("dd/mm/yyyy");
        fechaEntradaTxtField.setBorder(null);
        fechaEntradaTxtField.setPreferredSize(new java.awt.Dimension(240, 29));

        pesoTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pesoTxt.setText("Peso (Kg)");
        pesoTxt.setPreferredSize(new java.awt.Dimension(90, 30));

        pesoTxtField.setBackground(new java.awt.Color(232, 232, 232));
        pesoTxtField.setForeground(new java.awt.Color(153, 153, 153));
        pesoTxtField.setBorder(null);

        especieTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        especieTxt.setText("Especie");
        especieTxt.setPreferredSize(new java.awt.Dimension(90, 30));

        especieComboBox.setBackground(new java.awt.Color(232, 232, 232));
        especieComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige una especie", "Ave", "Mamifero", "Reptil" }));
        especieComboBox.setBorder(null);
        especieComboBox.setMinimumSize(new java.awt.Dimension(240, 29));
        especieComboBox.setPreferredSize(new java.awt.Dimension(240, 29));
        especieComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                especieComboBoxItemStateChanged(evt);
            }
        });

        motivoEspecialTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        motivoEspecialTxt.setText("Motivo especial");
        motivoEspecialTxt.setPreferredSize(new java.awt.Dimension(90, 30));

        gravedadTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gravedadTxt.setText("Gravedad");
        gravedadTxt.setPreferredSize(new java.awt.Dimension(90, 30));

        gravedadComboBox.setBackground(new java.awt.Color(232, 232, 232));
        gravedadComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baja", "Mediana", "Alta" }));
        gravedadComboBox.setBorder(null);
        gravedadComboBox.setMinimumSize(new java.awt.Dimension(240, 29));
        gravedadComboBox.setPreferredSize(new java.awt.Dimension(240, 29));

        razaTxtField1.setBackground(new java.awt.Color(232, 232, 232));
        razaTxtField1.setForeground(new java.awt.Color(153, 153, 153));
        razaTxtField1.setBorder(null);
        razaTxtField1.setMinimumSize(new java.awt.Dimension(240, 29));
        razaTxtField1.setPreferredSize(new java.awt.Dimension(240, 29));

        motivoEspecialCheckBox.setText("No deberias poder ver esto...");
        motivoEspecialCheckBox.setMinimumSize(new java.awt.Dimension(240, 29));
        motivoEspecialCheckBox.setPreferredSize(new java.awt.Dimension(240, 29));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(altaTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pesoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pesoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(razaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176)
                        .addComponent(fechaEntradaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gravedadComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gravedadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(motivoEspecialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(motivoEspecialCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lesionTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lesionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(razaTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(especieComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fechaEntradaTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(especieTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(343, 343, 343)
                .addComponent(crearAltaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(altaTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pesoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(razaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaEntradaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaEntradaTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(razaTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lesionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lesionTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(especieComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(especieTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(motivoEspecialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gravedadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gravedadComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(motivoEspecialCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(crearAltaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void crearAltaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearAltaBtnActionPerformed
        Animal newAnimal = null;
        String nombreAnimal, raza, tipoLesion, gravedad;
        double peso;
        boolean motivoEspecial;
        Date fechaEntrada;

        int indice = especieComboBox.getSelectedIndex();

        try {
            nombreAnimal = nameTxtField.getText();
            raza = razaTxtField1.getText();
            tipoLesion = lesionTxtField.getText();
            gravedad = gravedadComboBox.getSelectedItem().toString();
            peso = Double.parseDouble(pesoTxtField.getText());
            fechaEntrada = null;
            motivoEspecial = motivoEspecialCheckBox.isSelected();

//                    String fechaStr = "19/04/2024";
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            try {
                fechaEntrada = formato.parse(fechaEntradaTxtField.getText());
            } catch (ParseException e) {
                JOptionPane.showMessageDialog(null, "Formato de fecha incorrecto. Por favor, ingresa la fecha en formato dd/mm/yyyy", "Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }

            switch (indice) {
                case 1: // Ave
                    newAnimal = new Ave(motivoEspecial, nombreAnimal, raza, tipoLesion, gravedad, peso, fechaEntrada);
                    break;
                case 2: // Mamifero
                    newAnimal = new Mamifero(motivoEspecial, nombreAnimal, raza, tipoLesion, gravedad, peso, fechaEntrada);
                    break;
                case 3: // Reptil
                    newAnimal = new Reptil(motivoEspecial, nombreAnimal, raza, tipoLesion, gravedad, peso, fechaEntrada);
                    break;
                default:
                    throw new AssertionError();
            }

            CentroRecuperacionFauna.darAlta(newAnimal);
            JOptionPane.showMessageDialog(null, "Animal puesto");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al agregar animal");
        }
    }//GEN-LAST:event_crearAltaBtnActionPerformed

    private void especieComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_especieComboBoxItemStateChanged
        int indice = especieComboBox.getSelectedIndex();
        String texto = "Motivo: ";

        if (especieComboBox.getSelectedIndex() != 0) {
            switch (indice) {
                case 1: // Ave
                    texto += "Caza";
                    break;
                case 2: // Mamifero
                    texto += "Atropello";
                    break;
                case 3: // Reptil
                    texto += "Bacteriana";
                    break;
            }

            motivoEspecialCheckBox.setText(texto);
            motivoEspecialCheckBox.setEnabled(true);
        } else {
            motivoEspecialCheckBox.setText("Elige una especie");
            motivoEspecialCheckBox.setSelected(false);
            motivoEspecialCheckBox.setEnabled(false);
        }
    }//GEN-LAST:event_especieComboBoxItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel altaTitle;
    private javax.swing.JButton crearAltaBtn;
    private javax.swing.JComboBox<String> especieComboBox;
    private javax.swing.JLabel especieTxt;
    private javax.swing.JLabel fechaEntradaTxt;
    private javax.swing.JTextField fechaEntradaTxtField;
    private javax.swing.JComboBox<String> gravedadComboBox;
    private javax.swing.JLabel gravedadTxt;
    private javax.swing.JLabel lesionTxt;
    private javax.swing.JTextField lesionTxtField;
    private javax.swing.JCheckBox motivoEspecialCheckBox;
    private javax.swing.JLabel motivoEspecialTxt;
    private javax.swing.JLabel nameTxt;
    private javax.swing.JTextField nameTxtField;
    private javax.swing.JLabel pesoTxt;
    private javax.swing.JTextField pesoTxtField;
    private javax.swing.JLabel razaTxt;
    private javax.swing.JTextField razaTxtField1;
    // End of variables declaration//GEN-END:variables
}
