/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panels;

import com.mycompany.pr_dam_p5_gabriel_david.Animal;
import com.mycompany.pr_dam_p5_gabriel_david.Baja;
import com.mycompany.pr_dam_p5_gabriel_david.CentroRecuperacionFauna;
import com.mycompany.pr_dam_p5_gabriel_david.Veterinario;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 * Clase que representa el menú de Baja de animales del centro de recuperación de fauna.
 * En el Se puede dar de Baja un animal indicandolo mediante su respectivo ComboBox, el veterinario responsable del registro y la fecha del registro del fallecimiento.
 * 
 * @author David López Corella
 * @author Jesús Gabriel Pollos Villazón
 */
public class bajaPanel extends javax.swing.JPanel {

    /**
     * Creates new form altaPanel
     */
    public bajaPanel() {
        initComponents();
        cargarAnimales();

        animalComboBox.setSelectedIndex(-1);
        veterinariosComboBox.setSelectedIndex(-1);
    }

    private void cargarAnimales() {
        // Animal
        Vector animalComboBoxItems = new Vector();

        for (Animal animal : CentroRecuperacionFauna.getAnimales()) {
            animalComboBoxItems.add(animal.getNombreAnimal() + " (" + animal.getRaza() + ")");
        }

        final DefaultComboBoxModel animalModel = new DefaultComboBoxModel(animalComboBoxItems);
        animalComboBox.setModel(animalModel);

        // Veterinario
        Vector veterinarioComboBoxItems = new Vector();

        for (Veterinario veterinario : CentroRecuperacionFauna.getVeterinarios()) {
            veterinarioComboBoxItems.add(veterinario.getNombre() + " (" + veterinario.getEspecialidad() + ")");
        }

        final DefaultComboBoxModel veterinarioModel = new DefaultComboBoxModel(veterinarioComboBoxItems);
        veterinariosComboBox.setModel(veterinarioModel);
    }

    private void comprobarCombosParaBoton() {
        int indiceAnimal = animalComboBox.getSelectedIndex();
        int indiceVeterinario = veterinariosComboBox.getSelectedIndex();

        if (indiceAnimal == -1 || indiceVeterinario == -1) {
            bajaBtn.setEnabled(false);
        } else {
            bajaBtn.setEnabled(true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bajaTitle = new javax.swing.JLabel();
        veterinarioTxt = new javax.swing.JLabel();
        pacienteTxt = new javax.swing.JLabel();
        animalComboBox = new javax.swing.JComboBox<>();
        bajaBtn = new javax.swing.JButton();
        fechaBajaTxt = new javax.swing.JLabel();
        fechaBajaTxtField = new javax.swing.JTextField();
        veterinariosComboBox = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(860, 500));

        bajaTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bajaTitle.setForeground(new java.awt.Color(51, 153, 255));
        bajaTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bajaTitle.setText("Baja de un animal");

        veterinarioTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        veterinarioTxt.setText("Veterinario responsable");
        veterinarioTxt.setPreferredSize(new java.awt.Dimension(90, 30));

        pacienteTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pacienteTxt.setText("Paciente a dar de baja");
        pacienteTxt.setPreferredSize(new java.awt.Dimension(90, 30));

        animalComboBox.setBackground(new java.awt.Color(232, 232, 232));
        animalComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        animalComboBox.setBorder(null);
        animalComboBox.setMinimumSize(new java.awt.Dimension(72, 29));
        animalComboBox.setPreferredSize(new java.awt.Dimension(240, 29));
        animalComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animalComboBoxActionPerformed(evt);
            }
        });

        bajaBtn.setBackground(new java.awt.Color(0, 102, 255));
        bajaBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bajaBtn.setForeground(new java.awt.Color(255, 255, 255));
        bajaBtn.setText("DAR DE BAJA");
        bajaBtn.setBorder(null);
        bajaBtn.setHideActionText(true);
        bajaBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bajaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajaBtnActionPerformed(evt);
            }
        });

        fechaBajaTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fechaBajaTxt.setText("Fecha de baja");
        fechaBajaTxt.setPreferredSize(new java.awt.Dimension(90, 30));

        fechaBajaTxtField.setBackground(new java.awt.Color(232, 232, 232));
        fechaBajaTxtField.setForeground(new java.awt.Color(102, 102, 102));
        fechaBajaTxtField.setText("dd/mm/yyyy");
        fechaBajaTxtField.setBorder(null);
        fechaBajaTxtField.setPreferredSize(new java.awt.Dimension(240, 29));

        veterinariosComboBox.setBackground(new java.awt.Color(232, 232, 232));
        veterinariosComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jóse", "Andrea", "Alejandra", "Alejandro" }));
        veterinariosComboBox.setBorder(null);
        veterinariosComboBox.setPreferredSize(new java.awt.Dimension(240, 29));
        veterinariosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veterinariosComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bajaTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pacienteTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(animalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(veterinarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaBajaTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaBajaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(veterinariosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(bajaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(313, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bajaTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pacienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(animalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(veterinarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(veterinariosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fechaBajaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addComponent(fechaBajaTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(bajaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void animalComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animalComboBoxActionPerformed
        comprobarCombosParaBoton();
    }//GEN-LAST:event_animalComboBoxActionPerformed

    private void veterinariosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veterinariosComboBoxActionPerformed
        comprobarCombosParaBoton();
    }//GEN-LAST:event_veterinariosComboBoxActionPerformed

    private void bajaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajaBtnActionPerformed
        try {
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            int indicePaciente = animalComboBox.getSelectedIndex();

            CentroRecuperacionFauna.darBaja(indicePaciente, new Baja(
                    CentroRecuperacionFauna.getAnimales().get(indicePaciente),
                    formato.parse(fechaBajaTxtField.getText()),
                    CentroRecuperacionFauna.getVeterinarios().get(veterinariosComboBox.getSelectedIndex())
            ));
            JOptionPane.showMessageDialog(this, "Animal fallecido registrado correctamente");
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Formato de fecha incorrecto. Por favor, ingresa la fecha en formato dd/mm/yyyy", "Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(liberacionPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bajaBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> animalComboBox;
    private javax.swing.JButton bajaBtn;
    private javax.swing.JLabel bajaTitle;
    private javax.swing.JLabel fechaBajaTxt;
    private javax.swing.JTextField fechaBajaTxtField;
    private javax.swing.JLabel pacienteTxt;
    private javax.swing.JLabel veterinarioTxt;
    private javax.swing.JComboBox<String> veterinariosComboBox;
    // End of variables declaration//GEN-END:variables
}
