/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Panels;

import java.awt.BorderLayout;
import javax.swing.ImageIcon;

/**
 * Clase que representa el menú principal del centro de recuperación de fauna, de él nacen las demás ventanas.
 * 
 * @author David López Corella
 * @author Jesús Gabriel Pollos Villazón
 */
public class principalMenue extends javax.swing.JFrame {

    /**
     * Creates new form principalMenue
     */
    public principalMenue() {
        initComponents();
        setTitle("Centro de recuperación de fauna salvaje");
        setIconImage(new ImageIcon(getClass().getResource("/Imgs/Icon.png")).getImage());
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menuePanel = new javax.swing.JPanel();
        menuTxt = new javax.swing.JLabel();
        bajaBtn = new javax.swing.JButton();
        liberarBtn = new javax.swing.JButton();
        altaBtn = new javax.swing.JButton();
        tratamientoBtn = new javax.swing.JButton();
        listarBtn = new javax.swing.JButton();
        panelPrincipal = new javax.swing.JPanel();
        imagen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1125, 539));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuePanel.setBackground(new java.awt.Color(51, 153, 255));
        menuePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuTxt.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        menuTxt.setForeground(new java.awt.Color(255, 255, 255));
        menuTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuTxt.setText("MENÚ");
        menuePanel.add(menuTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 250, 86));

        bajaBtn.setBackground(new java.awt.Color(0, 102, 204));
        bajaBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bajaBtn.setForeground(new java.awt.Color(255, 255, 255));
        bajaBtn.setText("Dar de baja");
        bajaBtn.setBorder(null);
        bajaBtn.setPreferredSize(new java.awt.Dimension(250, 80));
        bajaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajaBtnActionPerformed(evt);
            }
        });
        menuePanel.add(bajaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        liberarBtn.setBackground(new java.awt.Color(0, 102, 204));
        liberarBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        liberarBtn.setForeground(new java.awt.Color(255, 255, 255));
        liberarBtn.setText("Liberación");
        liberarBtn.setBorder(null);
        liberarBtn.setPreferredSize(new java.awt.Dimension(250, 80));
        liberarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liberarBtnActionPerformed(evt);
            }
        });
        menuePanel.add(liberarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, -1));

        altaBtn.setBackground(new java.awt.Color(0, 102, 204));
        altaBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        altaBtn.setForeground(new java.awt.Color(255, 255, 255));
        altaBtn.setText("Dar de alta a\n un animal");
        altaBtn.setBorder(null);
        altaBtn.setPreferredSize(new java.awt.Dimension(250, 80));
        altaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaBtnActionPerformed(evt);
            }
        });
        menuePanel.add(altaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        tratamientoBtn.setBackground(new java.awt.Color(0, 102, 204));
        tratamientoBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tratamientoBtn.setForeground(new java.awt.Color(255, 255, 255));
        tratamientoBtn.setText("Tratamientos");
        tratamientoBtn.setBorder(null);
        tratamientoBtn.setPreferredSize(new java.awt.Dimension(250, 80));
        tratamientoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tratamientoBtnActionPerformed(evt);
            }
        });
        menuePanel.add(tratamientoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        listarBtn.setBackground(new java.awt.Color(0, 102, 204));
        listarBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        listarBtn.setForeground(new java.awt.Color(255, 255, 255));
        listarBtn.setText("Listar");
        listarBtn.setBorder(null);
        listarBtn.setPreferredSize(new java.awt.Dimension(250, 80));
        listarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarBtnActionPerformed(evt);
            }
        });
        menuePanel.add(listarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, -1, -1));

        jPanel1.add(menuePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 500));

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/logo.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CENTRO DE RECUPERACIÓN DE FAUNA SALVAJE");

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jPanel1.add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 860, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1125, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tratamientoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tratamientoBtnActionPerformed
        tratamientosPanel t1Panel = new tratamientosPanel();
        t1Panel.setSize(860, 500);
        t1Panel.setLocation(0, 0);

        panelPrincipal.removeAll();
        panelPrincipal.add(t1Panel, BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_tratamientoBtnActionPerformed

    private void liberarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liberarBtnActionPerformed
        liberacionPanel L1Panel = new liberacionPanel();
        L1Panel.setSize(860, 500);
        L1Panel.setLocation(0, 0);

        panelPrincipal.removeAll();
        panelPrincipal.add(L1Panel, BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_liberarBtnActionPerformed

    private void listarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarBtnActionPerformed
        listarPanel ListPanel = new listarPanel();
        ListPanel.setSize(860, 500);
        ListPanel.setLocation(0, 0);

        panelPrincipal.removeAll();
        panelPrincipal.add(ListPanel, BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_listarBtnActionPerformed

    private void bajaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajaBtnActionPerformed
        bajaPanel BajaPanel = new bajaPanel();
        BajaPanel.setSize(860, 500);
        BajaPanel.setLocation(0, 0);

        panelPrincipal.removeAll();
        panelPrincipal.add(BajaPanel, BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_bajaBtnActionPerformed
    
    private void altaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaBtnActionPerformed
        altaPanel a1 = new altaPanel();
        a1.setSize(860, 500);
        a1.setLocation(0, 0);

        panelPrincipal.removeAll();
        panelPrincipal.add(a1, BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_altaBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principalMenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principalMenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principalMenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principalMenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principalMenue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton altaBtn;
    private javax.swing.JButton bajaBtn;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton liberarBtn;
    private javax.swing.JButton listarBtn;
    private javax.swing.JLabel menuTxt;
    private javax.swing.JPanel menuePanel;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JButton tratamientoBtn;
    // End of variables declaration//GEN-END:variables
}
