/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panels;

import com.mycompany.pr_dam_p5_gabriel_david.Animal;
import com.mycompany.pr_dam_p5_gabriel_david.CentroRecuperacionFauna;
import com.mycompany.pr_dam_p5_gabriel_david.Tratamiento;
import com.mycompany.pr_dam_p5_gabriel_david.Veterinario;
import java.text.SimpleDateFormat;
import java.util.Vector;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 * Clase que representa el menú de Tratamientos de animales del centro de
 * recuperación de fauna. En el Se puede dar de Baja un animal indicandolo
 * mediante su respectivo ComboBox, el veterinario responsable del tratamiento,
 * el tipo de tratamiento que se va a dar y la fecha del registro.
 *
 * @author David López Corella
 * @author Jesús Gabriel Pollos Villazón
 */
public class tratamientosPanel extends javax.swing.JPanel {

    /**
     * Creates new form altaPanel
     */
    public tratamientosPanel() {
        initComponents();
        cargarAnimales();

        animalComboBox.setSelectedIndex(-1);
        veterinariosComboBox.setSelectedIndex(-1);
    }

    private void cargarAnimales() {
        // Animal
        Vector animalComboBoxItems = new Vector();

        for (Animal animal : CentroRecuperacionFauna.getAnimales()) {
            animalComboBoxItems.add(animal.getNombreAnimal() + " (" + animal.getRaza() + ")");
        }

        final DefaultComboBoxModel animalModel = new DefaultComboBoxModel(animalComboBoxItems);
        animalComboBox.setModel(animalModel);

        // Veterinario
        Vector veterinarioComboBoxItems = new Vector();

        for (Veterinario veterinario : CentroRecuperacionFauna.getVeterinarios()) {
            veterinarioComboBoxItems.add(veterinario.getNombre() + " (" + veterinario.getEspecialidad() + ")");
        }

        final DefaultComboBoxModel veterinarioModel = new DefaultComboBoxModel(veterinarioComboBoxItems);
        veterinariosComboBox.setModel(veterinarioModel);
    }

    private void comprobarCombosParaBoton() {
        int indiceAnimal = animalComboBox.getSelectedIndex();
        int indiceVeterinario = veterinariosComboBox.getSelectedIndex();

        if (indiceAnimal == -1 || indiceVeterinario == -1) {
            guardarTratamientoBtn.setEnabled(false);
        } else {
            guardarTratamientoBtn.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tratameintoTitle = new javax.swing.JLabel();
        tratamientoTxt = new javax.swing.JLabel();
        tratamientoTxtField = new javax.swing.JTextField();
        pacienteTxt = new javax.swing.JLabel();
        animalComboBox = new javax.swing.JComboBox<>();
        guardarTratamientoBtn = new javax.swing.JButton();
        veterinariosTxt = new javax.swing.JLabel();
        veterinariosComboBox = new javax.swing.JComboBox<>();
        fechaTratamientoTxt = new javax.swing.JLabel();
        fechaTratamientoTxtField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(860, 500));

        tratameintoTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tratameintoTitle.setForeground(new java.awt.Color(51, 153, 255));
        tratameintoTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tratameintoTitle.setText("Tratamiento de un animal");

        tratamientoTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tratamientoTxt.setText("Tratamiento");
        tratamientoTxt.setPreferredSize(new java.awt.Dimension(90, 30));

        tratamientoTxtField.setBackground(new java.awt.Color(232, 232, 232));
        tratamientoTxtField.setForeground(new java.awt.Color(153, 153, 153));
        tratamientoTxtField.setBorder(null);
        tratamientoTxtField.setMinimumSize(new java.awt.Dimension(240, 29));
        tratamientoTxtField.setPreferredSize(new java.awt.Dimension(240, 29));

        pacienteTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pacienteTxt.setText("Paciente a realizar tratamiento");
        pacienteTxt.setPreferredSize(new java.awt.Dimension(90, 30));

        animalComboBox.setBackground(new java.awt.Color(232, 232, 232));
        animalComboBox.setBorder(null);
        animalComboBox.setMinimumSize(new java.awt.Dimension(240, 29));
        animalComboBox.setPreferredSize(new java.awt.Dimension(240, 29));
        animalComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animalComboBoxActionPerformed(evt);
            }
        });

        guardarTratamientoBtn.setBackground(new java.awt.Color(0, 102, 255));
        guardarTratamientoBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        guardarTratamientoBtn.setForeground(new java.awt.Color(255, 255, 255));
        guardarTratamientoBtn.setText("GUARDAR");
        guardarTratamientoBtn.setBorder(null);
        guardarTratamientoBtn.setPreferredSize(new java.awt.Dimension(150, 40));
        guardarTratamientoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarTratamientoBtnActionPerformed(evt);
            }
        });

        veterinariosTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        veterinariosTxt.setText("Veterinario responsable");
        veterinariosTxt.setPreferredSize(new java.awt.Dimension(90, 30));

        veterinariosComboBox.setBackground(new java.awt.Color(232, 232, 232));
        veterinariosComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jóse", "Andrea", "Alejandra", "Alejandro" }));
        veterinariosComboBox.setBorder(null);
        veterinariosComboBox.setMinimumSize(new java.awt.Dimension(240, 29));
        veterinariosComboBox.setPreferredSize(new java.awt.Dimension(240, 29));
        veterinariosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veterinariosComboBoxActionPerformed(evt);
            }
        });

        fechaTratamientoTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fechaTratamientoTxt.setText("Fecha de Tratamiento");

        fechaTratamientoTxtField.setBackground(new java.awt.Color(232, 232, 232));
        fechaTratamientoTxtField.setForeground(new java.awt.Color(102, 102, 102));
        fechaTratamientoTxtField.setText("dd/mm/yyyy");
        fechaTratamientoTxtField.setBorder(null);
        fechaTratamientoTxtField.setMaximumSize(new java.awt.Dimension(269, 2147483647));
        fechaTratamientoTxtField.setPreferredSize(new java.awt.Dimension(240, 29));
        fechaTratamientoTxtField.setScrollOffset(0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tratameintoTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tratamientoTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tratamientoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(animalComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pacienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(veterinariosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(veterinariosComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fechaTratamientoTxt)
                            .addComponent(fechaTratamientoTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(guardarTratamientoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tratameintoTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tratamientoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tratamientoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(animalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pacienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(veterinariosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(veterinariosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fechaTratamientoTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fechaTratamientoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(guardarTratamientoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void animalComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animalComboBoxActionPerformed
        comprobarCombosParaBoton();
    }//GEN-LAST:event_animalComboBoxActionPerformed
    /**
     * Maneja el evento de hacer clic en el botón "GUARDAR" para agregar un
     * nuevo tratamiento. Obtiene los datos del tratamiento del formulario, como
     * el nombre del tratamiento, el paciente, el veterinario responsable y la
     * fecha del tratamiento. Luego crea un nuevo objeto Tratamiento con estos
     * datos y lo agrega al centro de recuperación de fauna. Muestra un mensaje
     * de éxito si se agrega correctamente, de lo contrario, muestra un mensaje
     * de error.
     *
     * @param evt El evento de acción que desencadena este método (clic en el botón "GUARDAR").
     */
    private void guardarTratamientoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarTratamientoBtnActionPerformed
        Tratamiento newTratamiento = null;
        Veterinario veterinario;
        String nombreTratamiento;
        int indicePaciente;
        Animal paciente = null;

        try {
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            indicePaciente = animalComboBox.getSelectedIndex();

            nombreTratamiento = tratamientoTxtField.getText();
            paciente = CentroRecuperacionFauna.getAnimales().get(animalComboBox.getSelectedIndex());
            veterinario = CentroRecuperacionFauna.getVeterinarios().get(veterinariosComboBox.getSelectedIndex());

            newTratamiento = new Tratamiento(nombreTratamiento, veterinario, formato.parse(fechaTratamientoTxtField.getText()));
            CentroRecuperacionFauna.addTratamiento(indicePaciente, newTratamiento);
            JOptionPane.showMessageDialog(this, "Tratamiento agregado correctamente");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al agregar el tratamiento");
            e.printStackTrace();
        }
    }//GEN-LAST:event_guardarTratamientoBtnActionPerformed

    private void veterinariosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veterinariosComboBoxActionPerformed
        comprobarCombosParaBoton();
    }//GEN-LAST:event_veterinariosComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> animalComboBox;
    private javax.swing.JLabel fechaTratamientoTxt;
    private javax.swing.JTextField fechaTratamientoTxtField;
    private javax.swing.JButton guardarTratamientoBtn;
    private javax.swing.JLabel pacienteTxt;
    private javax.swing.JLabel tratameintoTitle;
    private javax.swing.JLabel tratamientoTxt;
    private javax.swing.JTextField tratamientoTxtField;
    private javax.swing.JComboBox<String> veterinariosComboBox;
    private javax.swing.JLabel veterinariosTxt;
    // End of variables declaration//GEN-END:variables
}
